const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://assets.weimgs.com/weimgs/rk/images/wcm/products/202040/0168/anton-solid-wood-bed-o.jpg',
      newFurniture: true,
      heart: false,
      addCompare: false,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      image:
        'https://ii1.pepperfry.com/media/catalog/product/e/n/568x625/enri-queen-size-bed-with-storage-in-wenge-finish-by-mintwud-enri-queen-size-bed-with-storage-in-weng-x4jyej.jpg',
      newFurniture: true,
      heart: true,
      addCompare: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.ulcdn.net/images/products/156488/slide/1332x726/Baltoro_High_Gloss_Hydraulic_Storage_Bed_King_1.jpg?1561442441',
      newFurniture: true,
      heart: false,
      addCompare: true,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://assets.pbimgs.com/pbimgs/ab/images/dp/wcm/202022/0016/claremont-bed-c.jpg',
      newFurniture: true,
      heart: true,
      addCompare: true,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSgYNv7AYfMiJ54VMgLC6HMDyxkAZ_CWQJ7Zw&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS9qLSe6I_g-Buc6-DRDUhv4PzyHGV68WunUg&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQhNBk-olTMxGdqE1bM-e7GXg-DpjYfR2xxKA&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.lovefurniture.co.uk/bmz_cache/8/882eaa107b0dc95a06592c8aacf8afc1.image.550x550.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://5.imimg.com/data5/FK/AG/MY-61548813/interior-designing-services-for-restaurant-building-500x500.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.shopify.com/s/files/1/2660/5202/products/ASHAGKBD_AC_1400x.jpg?v=1598897434',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://res-1.cloudinary.com/brosa-design/image/fetch/f_auto,q_auto:good/https://s3-ap-southeast-2.amazonaws.com/brosadesign.com/products/3553/original/bed-frame-queen-solid-acacia-wood-3-brosa.png',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://assets.floydhome.com/spree/images/949/slider/001_D_Masthead.jpg?1583913317',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.shopify.com/s/files/1/2062/9195/products/84234574_542775326337150_8612521073390387200_n_685x700.jpg?v=1589294249',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: 'https://www.andsotobed.co.uk/images/products/standard/214_641.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: 'https://s7d5.scene7.com/is/image/UrbanOutfitters/30073654_020_b',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQKbQfOW7F1pKXDd6C1g3tzarUbBXCTz8BQtw&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.fabindia.com/ccstore/v1/images/?source=/file/v7607727443901456531/products/10606474BD.f.01082019.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: 'https://media.jeromes.com/content/Image/products/MGN59MBBQ_G.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image: 'https://5.imimg.com/data5/NC/HV/MY-37555897/double-bed-500x500.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTEX1cP4_xH3WvpvKdtD4zXHWaZ9nSja4oKCA&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSXGcqFA1uKcclFu-qDMQon36RRoT0A0oBOxQ&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.royaloakindia.com/uploads/ROYIND-royaloak-sunway-queen-bed-lifestyle94.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.strefasypialni.pl/userdata/public/gfx/7076/Aranzacja-lozko-smart-bed-zlozonej.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://aarsunwoods.com/wp-content/uploads/2019/02/Wooden-Royal-King-Size-Bed-with-Side-Tables-UH-YT-46.jpg',
      newFurniture: true,
    },

    {
      id: 'aenean-ru-bristique-25',
      name: 'Aenean Ru Bristique 25',
      category: 'chair',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://content.valuecityfurniture.com/images/product/roxie_gray_accent-chair_2008335_753044.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-26',
      name: 'Aenean Ru Bristique 26',
      category: 'chair',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      image:
        'https://cb2.scene7.com/is/image/CB2/RueCambonOfficeChairSHS17_16x9/?$web_zoom_furn_hero$&190905021443&wid=1008&hei=567',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-27',
      name: 'Aenean Ru Bristique 27',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/116910/pexels-photo-116910.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-28',
      name: 'Aenean Ru Bristique 28',
      category: 'chair',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/1148955/pexels-photo-1148955.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-29',
      name: 'Aenean Ru Bristique 29',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/2082090/pexels-photo-2082090.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-30',
      name: 'Aenean Ru Bristique 30',
      category: 'chair',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/696407/pexels-photo-696407.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-31',
      name: 'Aenean Ru Bristique 31',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-32',
      name: 'Aenean Ru Bristique 32',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/106839/pexels-photo-106839.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-33',
      name: 'Aenean Ru Bristique 33',
      category: 'chair',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/2179214/pexels-photo-2179214.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-34',
      name: 'Aenean Ru Bristique 34',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/447592/pexels-photo-447592.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-35',
      name: 'Aenean Ru Bristique 35',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/247931/pexels-photo-247931.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-36',
      name: 'Aenean Ru Bristique 36',
      category: 'chair',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/3097112/pexels-photo-3097112.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-37',
      name: 'Aenean Ru Bristique 37',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/276534/pexels-photo-276534.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-38',
      name: 'Aenean Ru Bristique 38',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/1366872/pexels-photo-1366872.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-39',
      name: 'Aenean Ru Bristique 39',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/1080696/pexels-photo-1080696.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-40',
      name: 'Aenean Ru Bristique 40',
      category: 'chair',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/220749/pexels-photo-220749.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-41',
      name: 'Aenean Ru Bristique 41',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/2079249/pexels-photo-2079249.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-42',
      name: 'Aenean Ru Bristique 42',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/1390062/pexels-photo-1390062.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-43',
      name: 'Aenean Ru Bristique 43',
      category: 'chair',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/945225/pexels-photo-945225.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-44',
      name: 'Aenean Ru Bristique 44',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/3937174/pexels-photo-3937174.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-45',
      name: 'Aenean Ru Bristique 45',
      category: 'chair',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/3705539/pexels-photo-3705539.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-46',
      name: 'Aenean Ru Bristique 46',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/546228/pexels-photo-546228.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-47',
      name: 'Aenean Ru Bristique 47',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/827518/pexels-photo-827518.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-48',
      name: 'Aenean Ru Bristique 48',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://images.pexels.com/photos/161029/cottage-lake-water-nature-161029.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-49',
      name: 'Aenean Ru Bristique 49',
      category: 'sofa',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image: 'https://api-bw.vox.pl/file/product/main/noel_sofa_2_1_w700-h600-q85.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-50',
      name: 'Aenean Ru Bristique 50',
      category: 'sofa',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      image: 'https://birdmeble.pl/userdata/public/gfx/4367.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-51',
      name: 'Aenean Ru Bristique 51',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQHkZoG5Cch8hNjzyLzeXQ4UqCy7kxVx-P68g&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-52',
      name: 'Aenean Ru Bristique 52',
      category: 'sofa',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://lectus24.pl/86464-large_default/sofa-rozkladana-bogota-z-pojemnikiem.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-53',
      name: 'Aenean Ru Bristique 53',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSWpQScCAHnC8AXOyUS4UBwkhh_O5Ik6XJJcw&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-54',
      name: 'Aenean Ru Bristique 54',
      category: 'sofa',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://lectus24.pl/95912-large_default/sofa-dwuosobowa-catlyn-l-rozowa-welur.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-55',
      name: 'Aenean Ru Bristique 55',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQZ0wXcLD-lNmdJXVtaiFe0nJNm_SYIU2UNEA&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-56',
      name: 'Aenean Ru Bristique 56',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRDU-abg2eFY8IeWpGrqjkhw8paARewLanMSQ&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-57',
      name: 'Aenean Ru Bristique 57',
      category: 'sofa',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://e1.meble.pl/gfx/_zdjecia_e1/sklep_oferta/3/318/3318699/bnaroznik_nowoczesny_lumber_jack___etap_sofa___ind_6646445337.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-58',
      name: 'Aenean Ru Bristique 58',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://meblowy.salon/userdata/public/gfx/3152/Rozkladana-sofa-Corner-z-podnozkiem-niebieska.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-59',
      name: 'Aenean Ru Bristique 59',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://mebledoktor24.pl/1450-large_default/sofa-bolton-3-osobowa-rozkladana.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-60',
      name: 'Aenean Ru Bristique 60',
      category: 'sofa',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://www.vero.pl/userdata/public/gfx/9f5e6dad3182a43a0f4bfb50710306d6.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-61',
      name: 'Aenean Ru Bristique 61',
      category: 'table',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRXce_0SOR9Kuk_LsdCwW8st6zBhuQhErm2zg&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-62',
      name: 'Aenean Ru Bristique 62',
      category: 'table',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSq4jNf8UummCWi_c-K4YD2JaIhDnLyLyA43Q&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-63',
      name: 'Aenean Ru Bristique 63',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'table',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR0pS3v1jEqjgY1V6w9JaeVPImfPT_2tDXMsg&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-64',
      name: 'Aenean Ru Bristique 64',
      category: 'table',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://cdn.shopify.com/s/files/1/2660/5106/products/25591414_AC_19dc60be-0830-4b45-a629-581782ac083d_1400x.jpg?v=1571710873',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-65',
      name: 'Aenean Ru Bristique 65',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTfHM2WO0bmjMNZWL7aSM7hD1TrYtsVKtbbKA&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-66',
      name: 'Aenean Ru Bristique 66',
      category: 'table',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSgMtPUJJs6Xt71YLDgckVXY_LGtHS_dBe3Ug&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-67',
      name: 'Aenean Ru Bristique 67',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: 'https://images-na.ssl-images-amazon.com/images/I/418nx0pwnzL._SX425_.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-68',
      name: 'Aenean Ru Bristique 68',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://content3.jdmagicbox.com/comp/rajkot/u1/0281px281.x281.180917162044.g5u1/catalogue/bhavya-furniture-rajkot-wntny8mebd.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-69',
      name: 'Aenean Ru Bristique 69',
      category: 'table',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRjHLEKHR7dKepd47UEpRDAft0ltOwvNLN6Bg&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-70',
      name: 'Aenean Ru Bristique 70',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://i.pinimg.com/originals/10/c3/31/10c331ffc372aef5a3edc3a5415b91f1.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-71',
      name: 'Aenean Ru Bristique 71',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://i.pinimg.com/originals/d5/92/fa/d592fa54f845843a127d6dfbb79a0182.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-72',
      name: 'Aenean Ru Bristique 72',
      category: 'table',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTdyWDsssnJnv1_5C-MGfkJenIBI_qRvyMn1Q&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-73',
      name: 'Aenean Ru Bristique 73',
      category: 'dining',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://www.housingunits.co.uk/media/catalog/product/cache/8dc3298bba34b0846ef73bc138720a2d/a/d/ad6d5c90ed27f9b68e8e34b20d5b711b5486bade_s267___462071___e_1_1.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-74',
      name: 'Aenean Ru Bristique 74',
      category: 'dining',
      price: 30,
      oldPrice: '',
      stars: 2,
      promo: 'sale',
      image:
        'https://www.cruise1st.co.uk/blog/wp-content/uploads/2017/07/Fotolia_42404790_S.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-75',
      name: 'Aenean Ru Bristique 75',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'table',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTfL0A3q30mE_8BQNK-P3LXQAF6OUWsb2XevQ&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-76',
      name: 'Aenean Ru Bristique 76',
      category: 'dining',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRWbLF89raXiWs76jAbk5UBaXhQhyzewdBo2A&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-77',
      name: 'Aenean Ru Bristique 77',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSZCF3CTLp59ybhFICHgoG16fsb9sbmdnwPMQ&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-78',
      name: 'Aenean Ru Bristique 78',
      category: 'dining',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSSK6DXgJxAB5qGsbHj2lDrU5YtqF_rND47EA&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-79',
      name: 'Aenean Ru Bristique 79',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: 'https://survivalbg.info/wp-content/uploads/2018/06/dining.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-80',
      name: 'Aenean Ru Bristique 80',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSXprEz1jfsQqPdzazd1P9oSxkFj23tD0IPvg&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-81',
      name: 'Aenean Ru Bristique 81',
      category: 'dining',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://media02.living4media.com/previews/MTU5MDExMjQ0/13250937-Classic-kitchen-dining-room-with-seat-in-bay-window-and-door-leading-into-garden.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-82',
      name: 'Aenean Ru Bristique 82',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://www.e-restauracja.com/assets/artykul/2016-10-09/rs-2016-10dd-18.jpg',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-83',
      name: 'Aenean Ru Bristique 83',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSxUReSUM7s__ddS84sXfYznHhz07z1mAGrzw&usqp=CAU',
      newFurniture: true,
    },
    {
      id: 'aenean-ru-bristique-84',
      name: 'Aenean Ru Bristique 84',
      category: 'dining',
      price: 30,
      oldPrice: '$40',
      stars: 2,
      promo: 'sale',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcScThfCm3xP7sKpUdfn7aSt_nJf2Gr7nA8yBQ&usqp=CAU',
      newFurniture: true,
    },
  ],
  cart: {
    products: [],
  },
};

export default initialState;
